name: Cypress Health Check Testing
on:
  push:
    branches:
      - main
  schedule:
    # runs twice a day (at noon and midnight - UTC)
    - cron: "0 12,00 * * *"
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Cypress run
        uses: cypress-io/github-action@v6
